### PR TITLE
remove percolator type

### PR DESCRIPTION
**Pull request by sezag**

### CODE REVIEW

**Comment by romainruaud** [comment]
I guess it's breaking something with ES7 if you specify a type ?

**Comment by sezag** [comment]
I make a change to keep compatibility

**Comment by rbayet** [comment]
Hello @sezag,

Your change was included in #13 along with 2 other fixes.
A new 1.4.1 release will soon be available

Cheers !

**Comment by rbayet** [comment]
Change was included in #13 and adapted in #14 to keep ES6 compatibility.
Release 1.4.1 is available.

**Pull request closed without merging**
